# Generated by Django 6.0.5 on 2026-06-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendedor / Comercial',
                'verbose_name_plural': 'Comerciais (Equipe)',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CLIENTE_FINAL', 'Cliente Final / Anunciante'), ('AGENCIA', 'Agência de Publicidade')], max_length=20)),
                ('segmento', models.CharField(blank=True, max_length=100, null=True)),
                ('vendedor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.comercial')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_formato', models.CharField(choices=[('LED', 'Painel Digital LED'), ('BRT', 'Abrigo de Ônibus / BRT'), ('CENOGRAFICO', 'Projeto Cenográfico'), ('PROMO', 'Ação Promocional OOH')], max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estagio_funil', models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Qualificação'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Negociação'), ('FECHADO', 'Fechado (Contrato)'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=20)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_desfecho', models.DateField(blank=True, null=True)),
                ('link_maps', models.URLField(blank=True, null=True, verbose_name='Link Geolocalização OOH')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto do Ponto')),
                ('motivo_perda', models.TextField(blank=True, null=True)),
                ('agencia', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AGENCIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_agencia', to='comercial.cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='comercial.cliente')),
                ('vendedor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.comercial')),
            ],
        ),
    ]
