# Generated by Django 6.0.5 on 2026-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_notahistorico_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='foto_url',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='link_maps',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Proposta / Briefing'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='estagio_funil',
            field=models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('QUALIFICACAO', 'Briefing'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Negociação'), ('FECHADO', 'Fechado (Contrato)'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=20),
        ),
    ]
