# Generated by Django 6.0.5 on 2026-06-02 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_remove_oportunidade_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 10, 21, 7, 691160)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_followup',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Follow-up'),
        ),
    ]
