# Generated by Django 6.0.5 on 2026-06-02 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_oportunidade_criado_em_oportunidade_data_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição:'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='produto_formato',
            field=models.CharField(choices=[('LED', 'Painel LED'), ('BRT', 'BRT'), ('CENOGRAFICO', 'Cenografia'), ('PROMO', 'Promocional OOH')], max_length=20),
        ),
    ]
