# Generated by Django 6.0.5 on 2026-06-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_comercial_user_alter_oportunidade_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do contato'),
        ),
    ]
