# Generated by Django 6.0.5 on 2026-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_cliente_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='estagio_funil',
            field=models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('SOLICITACAO', 'Solicitação de Proposta'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Negociação'), ('FECHADO', 'Fechado'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=20),
        ),
    ]
