# Generated by Django 6.0.5 on 2026-06-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_comercial_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='comercial',
            options={'ordering': ['nome'], 'verbose_name': 'Vendedor / Comercial', 'verbose_name_plural': 'Comerciais (Equipe)'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-criada_em']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vendedor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comercial.comercial'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='estagio_funil',
            field=models.CharField(choices=[('PROSPECCAO', 'Prospecção'), ('SOLICITACAO', 'Solicitação de Proposta'), ('PROPOSTA', 'Proposta Enviada'), ('NEGOCIACAO', 'Negociação'), ('FECHADO', 'Fechado'), ('PERDIDO', 'Perdido')], db_index=True, default='PROSPECCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='vendedor_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.comercial'),
        ),
    ]
